modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/LatvianModder/Item-Filters/issues"

[[mods]]
modId="itemfilters"
version="${file.jarVersion}"
displayName="Item Filters"
authors="LatvianModder"
description='''
Adds Item Filters that can be used in other mods to filter multiple items in devices
'''
credits="TheCodedOne for porting to 1.14.3"

[[dependencies.itemfilters]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.itemfilters]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"